apiVersion: v1
kind: Pod
metadata:
  name: vault-apptest
spec:
  initContainers:
  - name: vault-init-container
    image: image-registry.openshift-image-registry.svc:5000/xplat-test/huytg-python:latest
    imagePullPolicy: Always
    # Environment variables needed for vault authentication injected from secret.   
    envFrom:
    - secretRef:
        name: vault-properties  
    volumeMounts:
      # path to store the secrets after fetched from vault
    - name: data
      mountPath: /vault/secret
  containers:
    # Application Container 1 
  - name: httpd
    image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
    ports:
      - containerPort: 8080
    volumeMounts:
    # App sources secret file from the same Volume which is mounted by Init container above
    - name: data
      mountPath: /vault/secret
  volumes:
  - name: data
    emptyDir: {}
